// Bundle third-party libraries into vendor/ as self-contained ES modules, and
// write THIRD_PARTY_LICENSES.md from the packages that actually end up bundled.
// Rerun only when a library version changes: `npm run vendor`.
import { build } from "esbuild";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const entries = ["plot", "interval-tree"];
const packages = new Map();

for (const name of entries) {
  const result = await build({
    entryPoints: [`vendor-src/${name}.js`],
    outfile: `vendor/${name}.js`,
    bundle: true,
    format: "esm",
    minify: true,
    legalComments: "eof",
    metafile: true,
    logLevel: "warning",
  });
  for (const input of Object.keys(result.metafile.inputs)) {
    const m = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
    if (m) packages.set(m[1], path.join("node_modules", m[1]));
  }
}

async function licenseText(dir) {
  const files = await readdir(dir);
  const file = files.find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  return file ? (await readFile(path.join(dir, file), "utf8")).trim() : null;
}

const sections = [];
for (const [name, dir] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  const pkg = JSON.parse(await readFile(path.join(dir, "package.json"), "utf8"));
  const text = await licenseText(dir);
  if (!text) throw new Error(`No license file found for ${name}`);
  sections.push(`## ${name}@${pkg.version} (${pkg.license})\n\n\`\`\`\n${text}\n\`\`\``);
}

await writeFile(
  "THIRD_PARTY_LICENSES.md",
  `# Third-party licenses\n\nGenerated by \`npm run vendor\`. These packages are bundled into \`vendor/\`\nand served with the app. Do not edit by hand.\n\n${sections.join("\n\n")}\n`,
);
console.log(`vendor/: ${entries.length} bundles, ${packages.size} packages`);
